@startuml

left to right direction

frame "Tmux Server" #Grey {
  frame "Session: Writing" as session_writing #White {
    frame "Window: Novel" as window_novel #Green {
      rectangle "Pane: Vim" as pane1
    }
    frame "Window: Notes" as window_notes #Green {
      rectangle "Pane: Vim" as pane2
    }
  }
  frame "Session: Coding" as session_coding #White {
    frame "Window: DevOps" as window_backend #Green {
      rectangle "Pane: Vim" as pane3
      rectangle "Pane: htop" as pane4
    }
    frame "Window: Front end" as window_frontend #Green {
      rectangle "Pane: Vim" as pane7
      rectangle "Pane: yarn" as pane8
    }
    frame "Window: Docs" as window_docs #Green {
      rectangle "Pane: Vim" as pane9
    }
  }
}

window_novel --[hidden]> window_notes
window_backend --[hidden]> window_frontend
window_frontend --[hidden]> window_docs

@enduml
